// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx50y3hpV6-MGAvVOa9P9aWneK4NiZbKQ',
    appId: '1:560209547140:web:63a5737796445dbe67d7d1',
    messagingSenderId: '560209547140',
    projectId: 'tpsyntheseyskuridov',
    authDomain: 'tpsyntheseyskuridov.firebaseapp.com',
    storageBucket: 'tpsyntheseyskuridov.appspot.com',
    measurementId: 'G-CV7VH0MKV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa1_tvDiULH8FQ73_ncVfGpgeXItu70LM',
    appId: '1:560209547140:android:522015388005a1db67d7d1',
    messagingSenderId: '560209547140',
    projectId: 'tpsyntheseyskuridov',
    storageBucket: 'tpsyntheseyskuridov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHensuj4BO5wFNaDb5FtqQIRIa8PiIzYw',
    appId: '1:560209547140:ios:6c0781fb827f424d67d7d1',
    messagingSenderId: '560209547140',
    projectId: 'tpsyntheseyskuridov',
    storageBucket: 'tpsyntheseyskuridov.appspot.com',
    iosClientId: '560209547140-th7daot439oefouuv9uf4a3njvf1k59o.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpSyntheseYskuridov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHensuj4BO5wFNaDb5FtqQIRIa8PiIzYw',
    appId: '1:560209547140:ios:888a683b34f76e3667d7d1',
    messagingSenderId: '560209547140',
    projectId: 'tpsyntheseyskuridov',
    storageBucket: 'tpsyntheseyskuridov.appspot.com',
    iosClientId: '560209547140-ableltphaf3ek1b1f6m8hadpk2d4iiht.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpSyntheseYskuridov.RunnerTests',
  );
}
